### ISSUE TITLE
Unable to start/create the environment on vso-plan-southeastasia

### ISSUE THREAD

**Issue by tyamamushi** [MicrosoftDocs/vsonline#343]
Hello, my environment on vso-plan-southeastasia are unable to start.
My browser is Google Chrome 81.0.4044.43(Official Build)(64 bit).
One of env is https://online.visualstudio.com/environment/14cb5021-8380-4dcd-98a5-eadc2609bed3
![image](https://user-images.githubusercontent.com/12667162/76416555-a88e2980-63de-11ea-8560-477a2f129668.png)
![image](https://user-images.githubusercontent.com/12667162/76416636-c9567f00-63de-11ea-898a-933f1c1f187c.png)

**Comment by cmbrose** [comment]
Hi @tyamamushi - sorry you're having issues and thanks for reporting! 

@edgonmsft - from the logs for the environment, it looks like an issue running the custom container, can you help here?

**Comment by edgonmsft** [comment]
HI @tyamamushi!

We had a transient issue in South East Asia that should be resolved by now. Can you confirm if it works by now?

Also the environments were created with no repository, right?

Thanks!

**Comment by tyamamushi** [comment]
I try to create new one(https://online.visualstudio.com/environment/dab9d2f5-725c-4981-bb9e-97555e87add5).
Still not woking...
![image](https://user-images.githubusercontent.com/12667162/76474080-d35b9a80-643d-11ea-9586-68b36822c6f2.png)
![image](https://user-images.githubusercontent.com/12667162/76474145-10279180-643e-11ea-9256-ed9a2a20aff6.png)

**Comment by tyamamushi** [comment]
And I created the environment with no repository.

**Comment by edgonmsft** [comment]
Hi @tyamamushi we have published some updates recently. Can you confirm if the issue is resolved or if you still encounter it?

**Comment by tyamamushi** [comment]
Hi @edgonmsft Unfortunatley your updates dose not resolved my issue.

I create the following new env, but get error code 1003.
https://online.visualstudio.com/environment/f4d9edf7-ba15-49d9-82bf-a55bb8205849

![image](https://user-images.githubusercontent.com/12667162/76928513-0e216f00-6925-11ea-91cb-c60377791f97.png)

![image](https://user-images.githubusercontent.com/12667162/76928524-15e11380-6925-11ea-8ee8-608806935899.png)

**Comment by tyamamushi** [comment]
Hi @edgonmsft I have been to able to start my environment, right now.
I saw the following screen on chrome browser, before getting the env.
![image](https://user-images.githubusercontent.com/12667162/77417000-13405b80-6e08-11ea-902c-4e42614bd8ae.png)

**Comment by edgonmsft** [comment]
Hi @tyamamushi!

That screen is a recent improvement where we will be showing the state of environment creation/resume.

After that did your environment(s) work as expected?

**Comment by tyamamushi** [comment]
Hi @edgonmsft, Yes it works as expected.

**Comment by edgonmsft** [comment]
Thanks! I'm going to close this issue if you need any more help please reach out!
