### ISSUE TITLE
Unable to add a different python interpreter(3.7).

### ISSUE THREAD

**Issue by ShyamPoovaiah** [MicrosoftDocs/vsonline#90]
'Add interpreter' does not show up on Command Palette. Using sudo apt-get install python3.6 also results in errors.
![vs_online_errors](https://user-images.githubusercontent.com/8288256/68290898-c35a3580-00ae-11ea-94fa-6f3c217db7fc.PNG)

Tried Conda also. Asks for a standalone installation of Conda.
Is there a way to directly install the same on the server?

**Comment by srivatsn** [comment]
@derekbekoe can you please take a look?

**Comment by srivatsn** [comment]
Related to https://github.com/microsoft/Oryx/issues/404?

**Comment by Chuxel** [comment]
@srivatsn Yep - same issue.

**Comment by jkeech** [comment]
@ShyamPoovaiah, the installation issues should be fixed with the latest version of the base image that we just rolled out. Can you try it out in a new environment (which will pick up the latest image)?

**Comment by ShyamPoovaiah** [comment]
I tried 'sudo apt-get install python3.6'. There are no errors on the terminal. But it still does not upgrade.
![image](https://user-images.githubusercontent.com/8288256/68582519-f0d52380-04a0-11ea-89db-98dc0ab7c14a.png)

Also, does not show up in the command palette as a available interpreter.
![image](https://user-images.githubusercontent.com/8288256/68582631-372a8280-04a1-11ea-81db-eb49c5e86ac6.png)

Should I try alternatives if any?

**Comment by jkeech** [comment]
Python 3.6 is not installed in the base image. Most of the instructions I see online for installing 3.6 into Debian 9 (which is what the base image is based on) recommend installing from source, such as https://websetnet.net/install-python-3-6-4-debian-9/. Can you try installing from source or following other directions to get 3.6 installed into the Debian 9 base image?

We will soon support providing custom Dockerfiles/images, so if you have a different image that already has 3.6 installed, you could use that as your environment's image instead. That work is being in #15.

**Comment by ShyamPoovaiah** [comment]
I tried installing from the source and it worked fine. Thank you :)

![image](https://user-images.githubusercontent.com/8288256/68638631-32f57800-0528-11ea-8222-148e6ab2e180.png)

**Comment by jkeech** [comment]
Great to hear! Thanks for confirming. I’m going to go ahead and close this issue since you’ve found a viable solution.
